uri: 'http://localhost:8080'
notauthkickmessage: '&cDu bist nicht berechtigt diesen Server zu betreten!'
joinmessage: '&aSpieler %prefix &6%player &ahat den Server betreten!'
quitmessage: '&aSpieler %prefix &6%player &ahat den Server verlassen!'
tablistheader: '&aWillkommen auf dem'
tablistfooter: '&4R&2G&1B &dSubserver'