name: RGBPluginTest
version: '1.0'
main: de.zeppy5.rgbplugintest.RGBPluginTest
api-version: '1.20'
commands:
  info:
    description: Lists information from the API.
    permission: api.info
  reloadapi:
    description: Reloads the information from the API.
    permission: api.reload
